### ISSUE TITLE
Read MS1 data to SummarizedExperiment

### ISSUE THREAD

**Issue by michaelwitting** [Metabolomics-MPC/NTAnnotationWorkflow#1]
Write function to read input table into `SummarizedExperiment`

**Comment by chufz** [comment]
Ok, i'll try to implement in what we have now

**Comment by michaelwitting** [comment]
Should be `https://github.com/RforMassSpectrometry/QFeatures` (Link: [QFeatures](https://github.com/RforMassSpectrometry/QFeatures)).

**Comment by michaelwitting** [comment]
We should also think about encoding the experimental design in the `QFeatures`. Can we have positive and negative mode data in the same object? That would make life easier.

**Comment by chufz** [comment]
I think the assay matrices in the middle need to have same dimensions, therefore unfortunately not

**Comment by michaelwitting** [comment]
Same dimensions or only same amount of samples?

**Comment by chufz** [comment]
same dimensions, which also means same number of features

**Comment by chufz** [comment]
Should be implemented now
