### ISSUE TITLE
Add different ppm/tollerance/rt parameters for MS1/MS2 annotation

### ISSUE THREAD

**Issue by chufz** [Metabolomics-MPC/NTAnnotationWorkflow#14]
May it will be beneficial to have two separate parameters for MS1/MS2? To be more precise in the MS1 annotation, and still tolerate those spectral libraries are may be acquired by MS with lower resolution? If you agree, I will change this.

**Comment by michaelwitting** [comment]
Yes, I think it is fair to have different parameters for MS1 and MS2. Please adjust accordingly.
