### ISSUE TITLE
Script input

### ISSUE THREAD

**Issue by michaelwitting** [Metabolomics-MPC/NTAnnotationWorkflow#3]
I think we can structure the input to the script a bit.
In our metabolomics experiments we typically have positive and negative mode data from the same LC method. We are currently working with `MetaboAnnotation` on functions to match between both ionization modes (Link: [#56](https://github.com/rformassspectrometry/MetaboAnnotation/issues/56)).
It would be nice if we can match at the end of the script the MS1 features between positive and negative ionization mode.
Therefore I'm suggesting the following input structure:

|Project folder
|param file (containing all tolerances, adducts for positive and negative etc...)
|-> pos
|--> input
|---> xxx.csv (MS1 feature table)
|---> xxx.mgf (MS1 and MS2 data)
|---> MS1_lib_ext (folder containing compound libraries for MS1 matching using only m/z values)
|---> MS1_lib_inhouse (folder containing compound librires for MS1 matching using m/z and RT/RI values)
|---> MS2_lib_ext (folder containing MS2 libraries for matching)
|---> MS2_lib_inhouse (folder containing MS2 libraries for matching, including RT/RI value)
|--> output
|->neg
|--> input
|---> xxx.csv (MS1 feature table)
|---> xxx.mgf (MS1 and MS2 data)
|---> MS1_lib_ext (folder containing compound libraries for MS1 matching using only m/z values)
|---> MS1_lib_inhouse (folder containing compound librires for MS1 matching using m/z and RT/RI values)
|---> MS2_lib_ext (folder containing MS2 libraries for matching)
|---> MS2_lib_inhouse (folder containing MS2 libraries for matching, including RT/RI value)
|--> output

The idea would be to then calc the R script from the command line with input the only input the project folder and then it runs.

What do you think @chufz ?

**Comment by michaelwitting** [comment]
Shall we have in the yaml file only a path to the MS2 libraries and read files from there. I would iterate over them if multiple libraries shall be used. The file type can identified with a regex on the file ending, e.g. `.mb` would use the MassBank backen and `.msp` the MSP backend

**Comment by chufz** [comment]
Yes i had something like this in mind, you can then decide in the settings file which of the libraries to use

**Comment by michaelwitting** [comment]
Done.
