### ISSUE TITLE
IDs for MS1 features

### ISSUE THREAD

**Issue by michaelwitting** [Metabolomics-MPC/NTAnnotationWorkflow#6]
Shall be create unique IDs for the MS1 features once the file is read? E.g. using the row number and a prefix.
For example using "FT0000001" or so? Or "POSFT000001" and "NEGFT000001". Could be handy for positive/negative mapping if it shall be performed.

**Comment by chufz** [comment]
Yes, i agree on that, this might also help for duplicated annotation alignment

**Comment by michaelwitting** [comment]
Done.
